before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - windows
    - darwin
  goarch:
    - amd64
archives:
- wrap_in_directory: true
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - README.md
    - LICENSE
    - example-scripts/**/*
  replacements:
    darwin: macOS
    windows: Windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
